package com.example.lenovo.myproject1;

import android.content.Context;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteOpenHelper;

/**
 * Created by Lenovo on 9/10/2017.
 */

public class Database extends SQLiteOpenHelper {
    public Database(Context context) {
        super(context, "project", null, 1);
    }
    String str="CREATE TABLE bus(bus_id INTEGER PRIMARY KEY AUTOINCREMENT,B_name VARCHAR(25),SOURCE VARCHAR(25),DESTINATION VARCHAR(25),DATE DATE,TIME TIME,AVALAIBILITY INT,PRICE INT)";
    String str1="CREATE TABLE user_detail(use_name VARCHAR(25),use_email VARCHAR(25),use_contact NUMBER, use_password VARCHAR(20),fav VARCHAR(25))";
    String str2="CREATE TABLE bus_avai(bus_id INT,seat_no INT,status VARCHAR(5))";
    @Override
    public void onCreate(SQLiteDatabase db) {
        db.execSQL(str);
        db.execSQL(str1);
        db.execSQL(str2);
        db.execSQL("INSERT INTO bus(B_name,SOURCE,DESTINATION ,DATE,TIME,AVALAIBILITY,PRICE)VALUES('Shivneri','pune','mumbai','20/09/2017','20:00:00',6,500);");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(1,1,'true')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(1,2,'false')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(1,3,'true')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(1,4,'true')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(1,5,'false')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(1,6,'false')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(1,7,'false')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(1,8,'false')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(1,9,'true')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(1,10,'true')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(1,11,'true')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(1,12,'false')");
        db.execSQL("INSERT INTO bus(B_name,SOURCE,DESTINATION ,DATE,TIME,AVALAIBILITY,PRICE)VALUES('Purple','pune','mumbai','20/09/2017','20:00:00',7,550);");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(2,1,'true')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(2,2,'false')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(2,3,'false')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(2,4,'true')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(2,5,'false')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(2,6,'false')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(2,7,'false')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(2,8,'false')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(2,9,'true')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(2,10,'true')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(2,11,'true')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(2,12,'false')");
        db.execSQL("INSERT INTO bus(B_name,SOURCE,DESTINATION ,DATE,TIME,AVALAIBILITY,PRICE)VALUES('Orange','pune','delhi','20/09/2017','19:00:00',8,800);");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(3,1,'true')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(3,2,'false')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(3,3,'true')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(3,4,'true')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(3,5,'false')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(3,6,'false')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(3,7,'false')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(3,8,'false')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(3,9,'false')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(3,10,'true')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(3,11,'false')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(3,12,'false')");
        db.execSQL("INSERT INTO bus(B_name,SOURCE,DESTINATION ,DATE,TIME,AVALAIBILITY,PRICE)VALUES('VRL','pune','delhi','20/09/2017','21:00:00',9,900);");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(4,1,'true')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(4,2,'false')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(4,3,'false')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(4,4,'true')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(4,5,'false')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(4,6,'false')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(4,7,'false')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(4,8,'false')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(4,9,'false')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(4,10,'true')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(4,11,'false')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(4,12,'false')");
        db.execSQL("INSERT INTO bus(B_name,SOURCE,DESTINATION ,DATE,TIME,AVALAIBILITY,PRICE)VALUES('Sharma','mumbai','pune','20/09/2017','19:00:00',5,600);");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(5,1,'true')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(5,2,'true')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(5,3,'true')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(5,4,'true')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(5,5,'false')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(5,6,'true')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(5,7,'false')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(5,8,'true')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(5,9,'false')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(5,10,'true')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(5,11,'false')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(5,12,'false')");
        db.execSQL("INSERT INTO bus(B_name,SOURCE,DESTINATION ,DATE,TIME,AVALAIBILITY,PRICE)VALUES('Shivam','mumbai','pune','20/09/2017','22:00:00',4,650);");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(6,1,'true')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(6,2,'true')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(6,3,'true')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(6,4,'true')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(6,5,'false')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(6,6,'true')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(6,7,'false')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(6,8,'true')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(6,9,'false')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(6,10,'true')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(6,11,'true')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(6,12,'false')");
        db.execSQL("INSERT INTO bus(B_name,SOURCE,DESTINATION ,DATE,TIME,AVALAIBILITY,PRICE)VALUES('Adnan','mumbai','delhi','20/09/2017','19:00:00',5,1600);");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(7,1,'true')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(7,2,'true')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(7,3,'true')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(7,4,'true')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(7,5,'false')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(7,6,'true')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(7,7,'false')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(7,8,'true')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(7,9,'false')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(7,10,'true')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(7,11,'false')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(7,12,'false')");
        db.execSQL("INSERT INTO bus(B_name,SOURCE,DESTINATION ,DATE,TIME,AVALAIBILITY,PRICE)VALUES('Purple','mumbai','delhi','20/09/2017','19:00:00',7,1600);");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(8,1,'true')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(8,2,'false')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(8,3,'true')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(8,4,'true')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(8,5,'false')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(8,6,'true')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(8,7,'false')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(8,8,'true')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(8,9,'false')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(8,10,'false')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(8,11,'false')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(8,12,'false')");
        db.execSQL("INSERT INTO bus(B_name,SOURCE,DESTINATION ,DATE,TIME,AVALAIBILITY,PRICE)VALUES('Sharma','delhi','pune','20/09/2017','19:00:00',5,600);");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(9,1,'true')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(9,2,'true')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(9,3,'true')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(9,4,'true')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(9,5,'false')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(9,6,'true')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(9,7,'false')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(9,8,'true')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(9,9,'false')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(9,10,'true')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(9,11,'false')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(9,12,'false')");
        db.execSQL("INSERT INTO bus(B_name,SOURCE,DESTINATION ,DATE,TIME,AVALAIBILITY,PRICE)VALUES('Shivam','delhi','pune','20/09/2017','22:00:00',4,650);");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(10,1,'true')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(10,2,'true')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(10,3,'true')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(10,4,'true')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(10,5,'false')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(10,6,'true')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(10,7,'false')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(10,8,'true')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(10,9,'false')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(10,10,'true')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(10,11,'true')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(10,12,'false')");
        db.execSQL("INSERT INTO bus(B_name,SOURCE,DESTINATION ,DATE,TIME,AVALAIBILITY,PRICE)VALUES('Adnan','delhi','mumbai','20/09/2017','19:00:00',5,1600);");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(11,1,'true')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(11,2,'true')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(11,3,'true')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(11,4,'true')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(11,5,'false')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(11,6,'true')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(11,7,'false')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(11,8,'true')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(11,9,'false')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(11,10,'true')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(11,11,'false')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(11,12,'false')");
        db.execSQL("INSERT INTO bus(B_name,SOURCE,DESTINATION ,DATE,TIME,AVALAIBILITY,PRICE)VALUES('Purple','delhi','mumbai','20/09/2017','19:00:00',7,1600);");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(12,1,'true')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(12,2,'false')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(12,3,'true')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(12,4,'true')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(12,5,'false')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(12,6,'true')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(12,7,'false')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(12,8,'true')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(12,9,'false')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(12,10,'false')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(12,11,'false')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(12,12,'false')");
        db.execSQL("INSERT INTO bus(B_name,SOURCE,DESTINATION ,DATE,TIME,AVALAIBILITY,PRICE)VALUES('Shivneri','pune','mumbai','21/09/2017','20:00:00',6,500);");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(13,1,'true')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(13,2,'false')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(13,3,'true')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(13,4,'true')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(13,5,'false')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(13,6,'false')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(13,7,'false')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(13,8,'false')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(13,9,'true')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(13,10,'true')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(13,11,'true')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(13,12,'false')");
        db.execSQL("INSERT INTO bus(B_name,SOURCE,DESTINATION ,DATE,TIME,AVALAIBILITY,PRICE)VALUES('Purple','pune','mumbai','21/09/2017','20:00:00',7,550);");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(14,1,'true')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(14,2,'false')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(14,3,'false')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(14,4,'true')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(14,5,'false')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(14,6,'false')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(14,7,'false')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(14,8,'false')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(14,9,'true')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(14,10,'true')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(14,11,'true')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(14,12,'false')");
        db.execSQL("INSERT INTO bus(B_name,SOURCE,DESTINATION ,DATE,TIME,AVALAIBILITY,PRICE)VALUES('Orange','pune','delhi','21/09/2017','19:00:00',8,800);");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(15,1,'true')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(15,2,'false')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(15,3,'true')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(15,4,'true')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(15,5,'false')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(15,6,'false')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(15,7,'false')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(15,8,'false')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(15,9,'false')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(15,10,'true')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(15,11,'false')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(15,12,'false')");
        db.execSQL("INSERT INTO bus(B_name,SOURCE,DESTINATION ,DATE,TIME,AVALAIBILITY,PRICE)VALUES('VRL','pune','delhi','21/09/2017','21:00:00',9,900);");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(16,1,'true')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(16,2,'false')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(16,3,'false')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(16,4,'true')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(16,5,'false')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(16,6,'false')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(16,7,'false')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(16,8,'false')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(16,9,'false')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(16,10,'true')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(16,11,'false')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(16,12,'false')");
        db.execSQL("INSERT INTO bus(B_name,SOURCE,DESTINATION ,DATE,TIME,AVALAIBILITY,PRICE)VALUES('Sharma','mumbai','pune','21/09/2017','19:00:00',5,600);");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(17,1,'true')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(17,2,'true')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(17,3,'true')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(17,4,'true')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(17,5,'false')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(17,6,'true')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(17,7,'false')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(17,8,'true')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(17,9,'false')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(17,10,'true')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(17,11,'false')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(17,12,'false')");
        db.execSQL("INSERT INTO bus(B_name,SOURCE,DESTINATION ,DATE,TIME,AVALAIBILITY,PRICE)VALUES('Shivam','mumbai','pune','21/09/2017','22:00:00',4,650);");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(18,1,'true')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(18,2,'true')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(18,3,'true')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(18,4,'true')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(18,5,'false')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(18,6,'true')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(18,7,'false')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(18,8,'true')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(18,9,'false')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(18,10,'true')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(18,11,'true')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(18,12,'false')");
        db.execSQL("INSERT INTO bus(B_name,SOURCE,DESTINATION ,DATE,TIME,AVALAIBILITY,PRICE)VALUES('Adnan','mumbai','delhi','21/09/2017','19:00:00',5,1600);");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(19,1,'true')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(19,2,'true')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(19,3,'true')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(19,4,'true')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(19,5,'false')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(19,6,'true')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(19,7,'false')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(19,8,'true')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(19,9,'false')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(19,10,'true')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(19,11,'false')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(19,12,'false')");
        db.execSQL("INSERT INTO bus(B_name,SOURCE,DESTINATION ,DATE,TIME,AVALAIBILITY,PRICE)VALUES('Purple','mumbai','delhi','21/09/2017','19:00:00',7,1600);");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(20,1,'true')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(20,2,'false')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(20,3,'true')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(20,4,'true')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(20,5,'false')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(20,6,'true')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(20,7,'false')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(20,8,'true')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(20,9,'false')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(20,10,'false')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(20,11,'false')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(20,12,'false')");
        db.execSQL("INSERT INTO bus(B_name,SOURCE,DESTINATION ,DATE,TIME,AVALAIBILITY,PRICE)VALUES('Sharma','delhi','pune','21/09/2017','19:00:00',5,600);");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(21,1,'true')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(21,2,'true')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(21,3,'true')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(21,4,'true')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(21,5,'false')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(21,6,'true')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(21,7,'false')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(21,8,'true')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(21,9,'false')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(21,10,'true')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(21,11,'false')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(21,12,'false')");
        db.execSQL("INSERT INTO bus(B_name,SOURCE,DESTINATION ,DATE,TIME,AVALAIBILITY,PRICE)VALUES('Shivam','delhi','pune','21/09/2017','22:00:00',4,650);");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(22,1,'true')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(22,2,'true')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(22,3,'true')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(22,4,'true')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(22,5,'false')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(22,6,'true')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(22,7,'false')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(22,8,'true')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(22,9,'false')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(22,10,'true')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(22,11,'true')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(22,12,'false')");
        db.execSQL("INSERT INTO bus(B_name,SOURCE,DESTINATION ,DATE,TIME,AVALAIBILITY,PRICE)VALUES('Adnan','delhi','mumbai','21/09/2017','19:00:00',5,1600);");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(23,1,'true')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(23,2,'true')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(23,3,'true')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(23,4,'true')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(23,5,'false')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(23,6,'true')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(23,7,'false')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(23,8,'true')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(23,9,'false')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(23,10,'true')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(23,11,'false')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(23,12,'false')");
        db.execSQL("INSERT INTO bus(B_name,SOURCE,DESTINATION ,DATE,TIME,AVALAIBILITY,PRICE)VALUES('Purple','delhi','mumbai','21/09/2017','19:00:00',7,1600);");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(24,1,'true')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(24,2,'false')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(24,3,'true')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(24,4,'true')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(24,5,'false')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(24,6,'true')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(24,7,'false')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(24,8,'true')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(24,9,'false')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(24,10,'false')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(24,11,'false')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(24,12,'false')");
        db.execSQL("INSERT INTO bus(B_name,SOURCE,DESTINATION ,DATE,TIME,AVALAIBILITY,PRICE)VALUES('Shivneri','pune','mumbai','22/09/2017','20:00:00',6,500);");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(25,1,'true')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(25,2,'false')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(25,3,'true')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(25,4,'true')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(25,5,'false')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(25,6,'false')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(25,7,'false')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(25,8,'false')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(25,9,'true')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(25,10,'true')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(25,11,'true')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(25,12,'false')");
        db.execSQL("INSERT INTO bus(B_name,SOURCE,DESTINATION ,DATE,TIME,AVALAIBILITY,PRICE)VALUES('Purple','pune','mumbai','22/09/2017','20:00:00',7,550);");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(26,1,'true')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(26,2,'false')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(26,3,'false')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(26,4,'true')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(26,5,'false')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(26,6,'false')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(26,7,'false')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(26,8,'false')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(26,9,'true')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(26,10,'true')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(26,11,'true')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(26,12,'false')");
        db.execSQL("INSERT INTO bus(B_name,SOURCE,DESTINATION ,DATE,TIME,AVALAIBILITY,PRICE)VALUES('Orange','pune','delhi','22/09/2017','19:00:00',8,800);");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(27,1,'true')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(27,2,'false')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(27,3,'true')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(27,4,'true')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(27,5,'false')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(27,6,'false')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(27,7,'false')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(27,8,'false')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(27,9,'false')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(27,10,'true')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(27,11,'false')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(27,12,'false')");
        db.execSQL("INSERT INTO bus(B_name,SOURCE,DESTINATION ,DATE,TIME,AVALAIBILITY,PRICE)VALUES('VRL','pune','delhi','22/09/2017','21:00:00',9,900);");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(28,1,'true')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(28,2,'false')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(28,3,'false')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(28,4,'true')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(28,5,'false')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(28,6,'false')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(28,7,'false')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(28,8,'false')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(28,9,'false')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(28,10,'true')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(28,11,'false')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(28,12,'false')");
        db.execSQL("INSERT INTO bus(B_name,SOURCE,DESTINATION ,DATE,TIME,AVALAIBILITY,PRICE)VALUES('Sharma','mumbai','pune','22/09/2017','19:00:00',5,600);");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(29,1,'true')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(29,2,'true')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(29,3,'true')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(29,4,'true')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(29,5,'false')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(29,6,'true')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(29,7,'false')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(29,8,'true')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(29,9,'false')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(29,10,'true')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(29,11,'false')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(29,12,'false')");
        db.execSQL("INSERT INTO bus(B_name,SOURCE,DESTINATION ,DATE,TIME,AVALAIBILITY,PRICE)VALUES('Shivam','mumbai','pune','22/09/2017','22:00:00',4,650);");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(30,1,'true')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(30,2,'true')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(30,3,'true')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(30,4,'true')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(30,5,'false')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(30,6,'true')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(30,7,'false')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(30,8,'true')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(30,9,'false')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(30,10,'true')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(30,11,'true')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(30,12,'false')");
        db.execSQL("INSERT INTO bus(B_name,SOURCE,DESTINATION ,DATE,TIME,AVALAIBILITY,PRICE)VALUES('Adnan','mumbai','delhi','22/09/2017','19:00:00',5,1600);");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(31,1,'true')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(31,2,'true')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(31,3,'true')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(31,4,'true')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(31,5,'false')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(31,6,'true')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(31,7,'false')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(31,8,'true')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(31,9,'false')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(31,10,'true')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(31,11,'false')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(31,12,'false')");
        db.execSQL("INSERT INTO bus(B_name,SOURCE,DESTINATION ,DATE,TIME,AVALAIBILITY,PRICE)VALUES('Purple','mumbai','delhi','22/09/2017','19:00:00',7,1600);");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(32,1,'true')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(32,2,'false')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(32,3,'true')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(32,4,'true')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(32,5,'false')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(32,6,'true')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(32,7,'false')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(32,8,'true')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(32,9,'false')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(32,10,'false')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(32,11,'false')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(32,12,'false')");
        db.execSQL("INSERT INTO bus(B_name,SOURCE,DESTINATION ,DATE,TIME,AVALAIBILITY,PRICE)VALUES('Sharma','delhi','pune','22/09/2017','19:00:00',5,600);");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(33,1,'true')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(33,2,'true')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(33,3,'true')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(33,4,'true')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(33,5,'false')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(33,6,'true')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(33,7,'false')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(33,8,'true')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(33,9,'false')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(33,10,'true')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(33,11,'false')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(33,12,'false')");
        db.execSQL("INSERT INTO bus(B_name,SOURCE,DESTINATION ,DATE,TIME,AVALAIBILITY,PRICE)VALUES('Shivam','delhi','pune','22/09/2017','22:00:00',4,650);");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(34,1,'true')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(34,2,'true')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(34,3,'true')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(34,4,'true')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(34,5,'false')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(34,6,'true')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(34,7,'false')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(34,8,'true')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(34,9,'false')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(34,10,'true')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(34,11,'true')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(34,12,'false')");
        db.execSQL("INSERT INTO bus(B_name,SOURCE,DESTINATION ,DATE,TIME,AVALAIBILITY,PRICE)VALUES('Adnan','delhi','mumbai','22/09/2017','19:00:00',5,1600);");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(35,1,'true')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(35,2,'true')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(35,3,'true')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(35,4,'true')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(35,5,'false')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(35,6,'true')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(35,7,'false')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(35,8,'true')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(35,9,'false')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(35,10,'true')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(35,11,'false')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(35,12,'false')");
        db.execSQL("INSERT INTO bus(B_name,SOURCE,DESTINATION ,DATE,TIME,AVALAIBILITY,PRICE)VALUES('Purple','delhi','mumbai','22/09/2017','19:00:00',7,1600);");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(36,1,'true')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(36,2,'false')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(36,3,'true')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(36,4,'true')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(36,5,'false')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(36,6,'true')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(36,7,'false')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(36,8,'true')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(36,9,'false')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(36,10,'false')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(36,11,'false')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(36,12,'false')");
        db.execSQL("INSERT INTO bus(B_name,SOURCE,DESTINATION ,DATE,TIME,AVALAIBILITY,PRICE)VALUES('Shivneri','pune','mumbai','23/09/2017','20:00:00',6,500);");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(37,1,'true')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(37,2,'false')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(37,3,'true')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(37,4,'true')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(37,5,'false')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(37,6,'false')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(37,7,'false')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(37,8,'false')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(37,9,'true')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(37,10,'true')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(37,11,'true')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(37,12,'false')");
        db.execSQL("INSERT INTO bus(B_name,SOURCE,DESTINATION ,DATE,TIME,AVALAIBILITY,PRICE)VALUES('Purple','pune','mumbai','23/09/2017','20:00:00',7,550);");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(38,1,'true')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(38,2,'false')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(38,3,'false')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(38,4,'true')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(38,5,'false')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(38,6,'false')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(38,7,'false')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(38,8,'false')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(38,9,'true')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(38,10,'true')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(38,11,'true')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(38,12,'false')");
        db.execSQL("INSERT INTO bus(B_name,SOURCE,DESTINATION ,DATE,TIME,AVALAIBILITY,PRICE)VALUES('Orange','pune','delhi','23/09/2017','19:00:00',8,800);");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(39,1,'true')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(39,2,'false')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(39,3,'true')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(39,4,'true')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(39,5,'false')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(39,6,'false')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(39,7,'false')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(39,8,'false')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(39,9,'false')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(39,10,'true')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(39,11,'false')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(39,12,'false')");
        db.execSQL("INSERT INTO bus(B_name,SOURCE,DESTINATION ,DATE,TIME,AVALAIBILITY,PRICE)VALUES('VRL','pune','delhi','23/09/2017','21:00:00',9,900);");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(40,1,'true')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(40,2,'false')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(40,3,'false')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(40,4,'true')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(40,5,'false')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(40,6,'false')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(40,7,'false')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(40,8,'false')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(40,9,'false')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(40,10,'true')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(40,11,'false')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(40,12,'false')");
        db.execSQL("INSERT INTO bus(B_name,SOURCE,DESTINATION ,DATE,TIME,AVALAIBILITY,PRICE)VALUES('Sharma','mumbai','pune','23/09/2017','19:00:00',5,600);");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(41,1,'true')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(41,2,'true')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(41,3,'true')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(41,4,'true')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(41,5,'false')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(41,6,'true')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(41,7,'false')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(41,8,'true')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(41,9,'false')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(41,10,'true')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(41,11,'false')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(41,12,'false')");
        db.execSQL("INSERT INTO bus(B_name,SOURCE,DESTINATION ,DATE,TIME,AVALAIBILITY,PRICE)VALUES('Shivam','mumbai','pune','23/09/2017','22:00:00',4,650);");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(42,1,'true')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(42,2,'true')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(42,3,'true')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(42,4,'true')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(42,5,'false')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(42,6,'true')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(42,7,'false')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(42,8,'true')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(42,9,'false')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(42,10,'true')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(42,11,'true')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(42,12,'false')");
        db.execSQL("INSERT INTO bus(B_name,SOURCE,DESTINATION ,DATE,TIME,AVALAIBILITY,PRICE)VALUES('Adnan','mumbai','delhi','23/09/2017','19:00:00',5,1600);");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(43,1,'true')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(43,2,'true')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(43,3,'true')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(43,4,'true')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(43,5,'false')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(43,6,'true')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(43,7,'false')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(43,8,'true')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(43,9,'false')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(43,10,'true')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(43,11,'false')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(43,12,'false')");
        db.execSQL("INSERT INTO bus(B_name,SOURCE,DESTINATION ,DATE,TIME,AVALAIBILITY,PRICE)VALUES('Purple','mumbai','delhi','23/09/2017','19:00:00',7,1600);");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(44,1,'true')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(44,2,'false')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(44,3,'true')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(44,4,'true')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(44,5,'false')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(44,6,'true')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(44,7,'false')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(44,8,'true')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(44,9,'false')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(44,10,'false')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(44,11,'false')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(44,12,'false')");
        db.execSQL("INSERT INTO bus(B_name,SOURCE,DESTINATION ,DATE,TIME,AVALAIBILITY,PRICE)VALUES('Sharma','delhi','pune','23/09/2017','19:00:00',5,600);");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(45,1,'true')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(45,2,'true')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(45,3,'true')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(45,4,'true')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(45,5,'false')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(45,6,'true')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(45,7,'false')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(45,8,'true')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(45,9,'false')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(45,10,'true')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(45,11,'false')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(45,12,'false')");
        db.execSQL("INSERT INTO bus(B_name,SOURCE,DESTINATION ,DATE,TIME,AVALAIBILITY,PRICE)VALUES('Shivam','delhi','pune','23/09/2017','22:00:00',4,650);");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(46,1,'true')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(46,2,'true')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(46,3,'true')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(46,4,'true')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(46,5,'false')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(46,6,'true')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(46,7,'false')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(46,8,'true')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(46,9,'false')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(46,10,'true')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(46,11,'true')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(46,12,'false')");
        db.execSQL("INSERT INTO bus(B_name,SOURCE,DESTINATION ,DATE,TIME,AVALAIBILITY,PRICE)VALUES('Adnan','delhi','mumbai','23/09/2017','19:00:00',5,1600);");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(47,1,'true')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(47,2,'true')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(47,3,'true')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(47,4,'true')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(47,5,'false')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(47,6,'true')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(47,7,'false')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(47,8,'true')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(47,9,'false')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(47,10,'true')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(47,11,'false')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(47,12,'false')");
        db.execSQL("INSERT INTO bus(B_name,SOURCE,DESTINATION ,DATE,TIME,AVALAIBILITY,PRICE)VALUES('Purple','delhi','mumbai','23/09/2017','19:00:00',7,1600);");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(48,1,'true')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(48,2,'false')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(48,3,'true')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(48,4,'true')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(48,5,'false')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(48,6,'true')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(48,7,'false')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(48,8,'true')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(48,9,'false')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(48,10,'false')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(48,11,'false')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(48,12,'false')");
        db.execSQL("INSERT INTO bus(B_name,SOURCE,DESTINATION ,DATE,TIME,AVALAIBILITY,PRICE)VALUES('Shivneri','pune','mumbai','24/09/2017','20:00:00',6,500);");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(49,1,'true')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(49,2,'false')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(49,3,'true')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(49,4,'true')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(49,5,'false')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(49,6,'false')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(49,7,'false')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(49,8,'false')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(49,9,'true')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(49,10,'true')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(49,11,'true')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(49,12,'false')");
        db.execSQL("INSERT INTO bus(B_name,SOURCE,DESTINATION ,DATE,TIME,AVALAIBILITY,PRICE)VALUES('Purple','pune','mumbai','24/09/2017','20:00:00',7,550);");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(50,1,'true')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(50,2,'false')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(50,3,'false')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(50,4,'true')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(50,5,'false')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(50,6,'false')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(50,7,'false')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(50,8,'false')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(50,9,'true')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(50,10,'true')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(50,11,'true')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(50,12,'false')");
        db.execSQL("INSERT INTO bus(B_name,SOURCE,DESTINATION ,DATE,TIME,AVALAIBILITY,PRICE)VALUES('Orange','pune','delhi','24/09/2017','19:00:00',8,800);");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(51,1,'true')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(51,2,'false')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(51,3,'true')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(51,4,'true')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(51,5,'false')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(51,6,'false')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(51,7,'false')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(51,8,'false')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(51,9,'false')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(51,10,'true')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(51,11,'false')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(51,12,'false')");
        db.execSQL("INSERT INTO bus(B_name,SOURCE,DESTINATION ,DATE,TIME,AVALAIBILITY,PRICE)VALUES('VRL','pune','delhi','24/09/2017','21:00:00',9,900);");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(52,1,'true')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(52,2,'false')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(52,3,'false')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(52,4,'true')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(52,5,'false')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(52,6,'false')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(52,7,'false')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(52,8,'false')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(52,9,'false')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(52,10,'true')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(52,11,'false')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(52,12,'false')");
        db.execSQL("INSERT INTO bus(B_name,SOURCE,DESTINATION ,DATE,TIME,AVALAIBILITY,PRICE)VALUES('Sharma','mumbai','pune','24/09/2017','19:00:00',5,600);");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(53,1,'true')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(53,2,'true')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(53,3,'true')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(53,4,'true')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(53,5,'false')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(53,6,'true')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(53,7,'false')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(53,8,'true')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(53,9,'false')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(53,10,'true')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(53,11,'false')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(53,12,'false')");
        db.execSQL("INSERT INTO bus(B_name,SOURCE,DESTINATION ,DATE,TIME,AVALAIBILITY,PRICE)VALUES('Shivam','mumbai','pune','24/09/2017','22:00:00',4,650);");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(54,1,'true')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(54,2,'true')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(54,3,'true')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(54,4,'true')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(54,5,'false')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(54,6,'true')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(54,7,'false')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(54,8,'true')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(54,9,'false')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(54,10,'true')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(54,11,'true')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(54,12,'false')");
        db.execSQL("INSERT INTO bus(B_name,SOURCE,DESTINATION ,DATE,TIME,AVALAIBILITY,PRICE)VALUES('Adnan','mumbai','delhi','24/09/2017','19:00:00',5,1600);");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(55,1,'true')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(55,2,'true')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(55,3,'true')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(55,4,'true')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(55,5,'false')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(55,6,'true')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(55,7,'false')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(55,8,'true')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(55,9,'false')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(55,10,'true')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(55,11,'false')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(55,12,'false')");
        db.execSQL("INSERT INTO bus(B_name,SOURCE,DESTINATION ,DATE,TIME,AVALAIBILITY,PRICE)VALUES('Purple','mumbai','delhi','24/09/2017','19:00:00',7,1600);");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(56,1,'true')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(56,2,'false')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(56,3,'true')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(56,4,'true')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(56,5,'false')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(56,6,'true')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(56,7,'false')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(56,8,'true')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(56,9,'false')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(56,10,'false')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(56,11,'false')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(56,12,'false')");
        db.execSQL("INSERT INTO bus(B_name,SOURCE,DESTINATION ,DATE,TIME,AVALAIBILITY,PRICE)VALUES('Sharma','delhi','pune','24/09/2017','19:00:00',5,600);");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(57,1,'true')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(57,2,'true')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(57,3,'true')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(57,4,'true')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(57,5,'false')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(57,6,'true')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(57,7,'false')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(57,8,'true')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(57,9,'false')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(57,10,'true')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(57,11,'false')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(57,12,'false')");
        db.execSQL("INSERT INTO bus(B_name,SOURCE,DESTINATION ,DATE,TIME,AVALAIBILITY,PRICE)VALUES('Shivam','delhi','pune','24/09/2017','22:00:00',4,650);");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(58,1,'true')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(58,2,'true')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(58,3,'true')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(58,4,'true')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(58,5,'false')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(58,6,'true')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(58,7,'false')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(58,8,'true')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(58,9,'false')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(58,10,'true')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(58,11,'true')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(58,12,'false')");
        db.execSQL("INSERT INTO bus(B_name,SOURCE,DESTINATION ,DATE,TIME,AVALAIBILITY,PRICE)VALUES('Adnan','delhi','mumbai','24/09/2017','19:00:00',5,1600);");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(59,1,'true')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(59,2,'true')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(59,3,'true')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(59,4,'true')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(59,5,'false')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(59,6,'true')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(59,7,'false')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(59,8,'true')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(59,9,'false')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(59,10,'true')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(59,11,'false')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(59,12,'false')");
        db.execSQL("INSERT INTO bus(B_name,SOURCE,DESTINATION ,DATE,TIME,AVALAIBILITY,PRICE)VALUES('Purple','delhi','mumbai','24/09/2017','19:00:00',7,1600);");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(60,1,'true')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(60,2,'false')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(60,3,'true')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(60,4,'true')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(60,5,'false')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(60,6,'true')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(60,7,'false')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(60,8,'true')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(60,9,'false')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(60,10,'false')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(60,11,'false')");
        db.execSQL("INSERT INTO bus_avai(bus_id,seat_no,status)VALUES(60,12,'false')");
    }

    @Override
    public void onUpgrade(SQLiteDatabase db, int oldVersion, int newVersion) {

    }
}
